;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="UI.Layer.HUD",DevComment="항상  표시되는 HUD (체력/스킬/데미지/스테이지 등)")
+GameplayTagList=(Tag="UI.Layer.Menu",DevComment="메인메뉴/인벤토리 등 전체 화면 메뉴")
+GameplayTagList=(Tag="UI.Layer.Modal",DevComment="일시정지/확인창 등 입력잠금 화면")
+GameplayTagList=(Tag="UI.Layer.Result",DevComment="사망/클리어 등 결과화면")
+GameplayTagList=(Tag="UI.Request.Clear",DevComment="클리어UI")
+GameplayTagList=(Tag="UI.Request.GameOver",DevComment="사망UI")
+GameplayTagList=(Tag="UI.Request.HUD",DevComment="HUD")
+GameplayTagList=(Tag="UI.Request.Inventory",DevComment="Open inventory screen")
+GameplayTagList=(Tag="UI.Request.MainMenu",DevComment="Open MainMenu Screen")
+GameplayTagList=(Tag="UI.Request.PauseMenu",DevComment="Open PauseMenu Screen")

